In [18]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np

In [10]:
# Generate 200 random samples with 2 features
np.random.seed(42)  # For reproducibility
x = np.random.randn(200, 2) * 2  # 200 samples, 2 features with some scaling
# Generate corresponding binary labels
y = np.where(x[:, 0] + x[:, 1] > 0, 1, 0)  # Simple decision boundary for binary classification



In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

array([[-0.88008897,  0.26148115],
       [ 0.48993314, -1.01388635],
       [-1.81604815, -2.8246074 ],
       [ 1.09419476, -0.4043853 ],
       [-0.07165208,  3.12928731],
       [ 1.38028798, -0.80244094],
       [-1.20127738, -0.5833875 ],
       [ 0.72327205, -1.29023951],
       [ 1.49458721,  1.22074053],
       [ 1.64508982, -2.4416873 ],
       [-1.98107265, -1.13259546],
       [ 2.28564563,  1.50386607],
       [ 4.24431239,  2.06493052],
       [-0.15420342,  0.68230395],
       [ 1.00997456,  1.73151039],
       [ 0.39811939, -1.20043375],
       [ 1.95023947, -0.29411476],
       [ 0.48392454, -3.82656049],
       [ 0.71557472,  1.12156905],
       [-1.83884847,  3.09986881],
       [-0.06942354, -2.33735608],
       [-3.03873993, -0.96846815],
       [ 2.88254658, -2.8717243 ],
       [ 2.90228722,  1.91854165],
       [ 1.29537708,  3.04605971],
       [ 2.06199904,  1.86256024],
       [-2.30198715,  0.75139604],
       [ 3.26482261, -2.86028276],
       [-0.30357019,

In [12]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train
x_test

array([[ 1.40107756e+00, -1.51688173e+00],
       [-2.04454816e-01,  2.99301602e-01],
       [ 1.46434092e+00, -2.62937043e-01],
       [ 3.13975502e-01, -9.04215030e-01],
       [ 2.04644039e-01, -1.35043299e+00],
       [ 9.10514696e-01,  3.28306577e-01],
       [ 4.77449203e-02, -1.24086003e+00],
       [-7.45960419e-01,  2.08578977e-01],
       [-6.76934112e-01,  8.86662700e-01],
       [-3.28162662e-01,  7.87010167e-01],
       [ 8.06969150e-01,  1.42382730e+00],
       [-9.43802983e-01, -8.56783389e-02],
       [ 2.24400578e-03,  1.52756335e+00],
       [-9.98736215e-01,  4.70488431e-01],
       [-4.93133921e-01, -2.20163483e-01],
       [ 2.13606712e+00, -2.10355059e+00],
       [ 2.67648312e-01,  8.59740763e-01],
       [ 5.94137062e-02, -4.33037578e-01],
       [-9.06143535e-01, -8.92038190e-01],
       [ 2.18097181e-01,  1.37147921e+00],
       [-4.74477874e-01,  1.10490439e+00],
       [ 8.94571675e-02, -5.59023347e-01],
       [ 8.15152476e-02, -2.14138097e+00],
       [ 8.

In [13]:
train=LogisticRegression()
train.fit(x_train,y_train)

LogisticRegression()

In [14]:
y_pre=train.predict(x_test)

In [15]:
y_test

array([1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0])

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pre)

1.0